
import Analizador.Ambito;
import SQL.TablaSimbolosMySQL;
import SQL.ControladorSQL;
import Excel.GenerarExcel;
import Modelos.NumeroLinea;
import Analizador.Lexico;
import Analizador.Semantica1;
import Analizador.Semantica2;
import Analizador.Sintaxis;
import Controladores.ControladorTokenError;
import Modelos.Semantica1.Arreglo;
import java.awt.Desktop;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map.Entry;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author marco
 */
public class Interfaz extends javax.swing.JFrame {

    Lexico analizadorLexico;
    Sintaxis analizadorSintaxis;
    Ambito analizadorAmbito;
    HashMap<String,Arreglo> arreglos;
    Semantica1 analizadorSemantica1;
    Semantica2 analizadorSemantica2;
    ControladorTokenError controladorTokenError;
    public static GenerarExcel generarExcel;
    ControladorSQL controladorSQL;
    String urlLog, nombreExcel;

    public Interfaz() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        cargarTextArea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        headerPanel = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        btnCargar = new javax.swing.JButton();
        btnXlsx = new javax.swing.JButton();
        btnTablaSimbolos = new javax.swing.JButton();
        jRBExcel = new javax.swing.JRadioButton();
        panelCompilar = new javax.swing.JPanel();
        btnCompilar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        panelTextArea = new javax.swing.JPanel();
        jSPTextArea = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelTablas = new javax.swing.JPanel();
        panelTokens = new javax.swing.JPanel();
        scrollPaneTokens = new javax.swing.JScrollPane();
        tablaTokens = new javax.swing.JTable();
        labelTokens = new javax.swing.JLabel();
        panelErrores = new javax.swing.JPanel();
        scrollPaneErrores = new javax.swing.JScrollPane();
        tablaErrores = new javax.swing.JTable();
        jLabelErrores = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnEjecutarUltimaPrueba = new javax.swing.JButton();
        btnAbrirLog = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRBLexico = new javax.swing.JRadioButton();
        jRBSintaxis = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new java.awt.Color(30, 30, 30));
        headerPanel.setLayout(new java.awt.GridLayout(1, 2));

        panelSuperior.setBackground(new java.awt.Color(0, 0, 0));

        btnCargar.setBackground(new java.awt.Color(51, 51, 51));
        btnCargar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCargar.setForeground(new java.awt.Color(255, 255, 255));
        btnCargar.setText("Cargar");
        btnCargar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnCargar.setContentAreaFilled(false);
        btnCargar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCargar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        btnXlsx.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnXlsx.setForeground(new java.awt.Color(255, 255, 255));
        btnXlsx.setText("Generar Excel");
        btnXlsx.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnXlsx.setContentAreaFilled(false);
        btnXlsx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXlsx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXlsxActionPerformed(evt);
            }
        });

        btnTablaSimbolos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTablaSimbolos.setForeground(new java.awt.Color(255, 255, 255));
        btnTablaSimbolos.setText("Tabla de Simbolos");
        btnTablaSimbolos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnTablaSimbolos.setContentAreaFilled(false);
        btnTablaSimbolos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTablaSimbolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaSimbolosActionPerformed(evt);
            }
        });

        jRBExcel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRBExcel.setForeground(new java.awt.Color(255, 255, 255));
        jRBExcel.setText("Abrir Excel");

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jRBExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addComponent(btnXlsx, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTablaSimbolos, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXlsx, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTablaSimbolos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRBExcel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        headerPanel.add(panelSuperior);

        panelCompilar.setBackground(new java.awt.Color(0, 0, 0));

        btnCompilar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnCompilar.setForeground(new java.awt.Color(255, 255, 255));
        btnCompilar.setText("Compilar");
        btnCompilar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        btnCompilar.setContentAreaFilled(false);
        btnCompilar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompilar.setMargin(new java.awt.Insets(2, 30, 30, 14));
        btnCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompilarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCompilarLayout = new javax.swing.GroupLayout(panelCompilar);
        panelCompilar.setLayout(panelCompilarLayout);
        panelCompilarLayout.setHorizontalGroup(
            panelCompilarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompilarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCompilar, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCompilarLayout.setVerticalGroup(
            panelCompilarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompilarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCompilar, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        headerPanel.add(panelCompilar);

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        panelPrincipal.setBackground(new java.awt.Color(30, 30, 30));
        panelPrincipal.setForeground(new java.awt.Color(30, 30, 30));
        panelPrincipal.setLayout(new javax.swing.BoxLayout(panelPrincipal, javax.swing.BoxLayout.LINE_AXIS));

        panelTextArea.setBackground(new java.awt.Color(30, 30, 30));

        jSPTextArea.setBackground(new java.awt.Color(0, 0, 0));
        jSPTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jSPTextArea.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea1.setBackground(new java.awt.Color(25, 25, 25));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jSPTextArea.setViewportView(jTextArea1);

        javax.swing.GroupLayout panelTextAreaLayout = new javax.swing.GroupLayout(panelTextArea);
        panelTextArea.setLayout(panelTextAreaLayout);
        panelTextAreaLayout.setHorizontalGroup(
            panelTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTextAreaLayout.setVerticalGroup(
            panelTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTextAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        panelPrincipal.add(panelTextArea);

        panelTablas.setBackground(new java.awt.Color(30, 30, 30));
        panelTablas.setLayout(new java.awt.BorderLayout());

        panelTokens.setBackground(new java.awt.Color(30, 30, 30));
        panelTokens.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 102), 3));
        panelTokens.setMaximumSize(new java.awt.Dimension(600, 32767));
        panelTokens.setPreferredSize(new java.awt.Dimension(600, 349));

        tablaTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Estado", "Lexema", "Linea"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaTokens.setSelectionBackground(new java.awt.Color(224, 255, 224));
        tablaTokens.setSelectionForeground(new java.awt.Color(51, 153, 0));
        scrollPaneTokens.setViewportView(tablaTokens);

        labelTokens.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelTokens.setForeground(new java.awt.Color(255, 255, 255));
        labelTokens.setText("Tokens");

        javax.swing.GroupLayout panelTokensLayout = new javax.swing.GroupLayout(panelTokens);
        panelTokens.setLayout(panelTokensLayout);
        panelTokensLayout.setHorizontalGroup(
            panelTokensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTokensLayout.createSequentialGroup()
                .addComponent(labelTokens)
                .addGap(621, 755, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTokensLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneTokens)
                .addContainerGap())
        );
        panelTokensLayout.setVerticalGroup(
            panelTokensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTokensLayout.createSequentialGroup()
                .addComponent(labelTokens)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneTokens, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelTablas.add(panelTokens, java.awt.BorderLayout.CENTER);

        panelErrores.setBackground(new java.awt.Color(30, 30, 30));
        panelErrores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 3));

        tablaErrores.setAutoCreateRowSorter(true);
        tablaErrores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Estado", "Descripcion", "Lexema", "Linea", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaErrores.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaErrores.setSelectionBackground(new java.awt.Color(255, 211, 211));
        tablaErrores.setSelectionForeground(new java.awt.Color(204, 0, 0));
        scrollPaneErrores.setViewportView(tablaErrores);

        jLabelErrores.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelErrores.setForeground(new java.awt.Color(255, 255, 255));
        jLabelErrores.setText("Errores");

        javax.swing.GroupLayout panelErroresLayout = new javax.swing.GroupLayout(panelErrores);
        panelErrores.setLayout(panelErroresLayout);
        panelErroresLayout.setHorizontalGroup(
            panelErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelErroresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelErroresLayout.createSequentialGroup()
                        .addComponent(jLabelErrores)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrollPaneErrores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelErroresLayout.setVerticalGroup(
            panelErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelErroresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelErrores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelTablas.add(panelErrores, java.awt.BorderLayout.PAGE_START);

        panelBotones.setBackground(new java.awt.Color(30, 30, 30));

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));

        btnEjecutarUltimaPrueba.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnEjecutarUltimaPrueba.setForeground(new java.awt.Color(255, 255, 255));
        btnEjecutarUltimaPrueba.setText("Ejecutar Última Prueba");
        btnEjecutarUltimaPrueba.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnEjecutarUltimaPrueba.setContentAreaFilled(false);
        btnEjecutarUltimaPrueba.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEjecutarUltimaPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarUltimaPruebaActionPerformed(evt);
            }
        });

        btnAbrirLog.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnAbrirLog.setForeground(new java.awt.Color(255, 255, 255));
        btnAbrirLog.setText("Abrir Log");
        btnAbrirLog.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btnAbrirLog.setContentAreaFilled(false);
        btnAbrirLog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbrirLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirLogActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(30, 30, 30));

        buttonGroup1.add(jRBLexico);
        jRBLexico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRBLexico.setForeground(new java.awt.Color(255, 255, 255));
        jRBLexico.setText("Léxico");
        jRBLexico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonGroup1.add(jRBSintaxis);
        jRBSintaxis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRBSintaxis.setForeground(new java.awt.Color(255, 255, 255));
        jRBSintaxis.setText("Sintaxis-Ambito-Semantica1");
        jRBSintaxis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRBLexico)
                .addGap(10, 10, 10)
                .addComponent(jRBSintaxis)
                .addContainerGap(535, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBLexico)
                    .addComponent(jRBSintaxis))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAbrirLog, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btnEjecutarUltimaPrueba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnEjecutarUltimaPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbrirLog, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelTablas.add(panelBotones, java.awt.BorderLayout.PAGE_END);

        panelPrincipal.add(panelTablas);

        jScrollPane1.setViewportView(panelPrincipal);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        String aux;
        String texto;
        File archivo;
        JFileChooser select = new JFileChooser();
        select.setMultiSelectionEnabled(false);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos txt", "txt");
        select.setFileFilter(filtro);
        int opcion = select.showOpenDialog(select);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            jTextArea1.setText("");
            try {
                archivo = new File(select.getSelectedFile() + "");
                FileReader archivos = new FileReader(archivo);
                BufferedReader leer = new BufferedReader(archivos);
                aux = leer.readLine();
                texto = aux;
                jTextArea1.append(texto);
                while ((aux = leer.readLine()) != null) {
                    texto = aux;
                    jTextArea1.append("\n" + texto);
                    System.out.println("{" + texto + "},");
                }
                leer.close();

            } catch (Exception ev) {
                JOptionPane.showMessageDialog(null, ev, "Error al abrir", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private String crearDirectorioLog() {
        LocalDateTime localDate = LocalDateTime.now();
        String url = "Log [" + localDate.getHour() + "-" + localDate.getMinute()
                + "-" + localDate.getSecond() + "]@[" + localDate.getDayOfMonth()
                + "-" + localDate.getMonth() + "" + "-" + localDate.getYear() + "]";
        File directorio = new File("logs/" + url);
        directorio.mkdir();
        return url;
    }

    private void btnCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarActionPerformed
        controladorSQL = new ControladorSQL();
        controladorSQL.limpiarTablaSimbolos();
        urlLog = crearDirectorioLog();
        arreglos = new HashMap<>();
        establecerUltimaPrueba();
        controladorTokenError = new ControladorTokenError(tablaTokens, tablaErrores);
        analizadorLexico = new Lexico(urlLog, controladorTokenError);
        analizadorLexico.iniciarLexico(jTextArea1);
        analizadorSemantica2 = new Semantica2(arreglos);
        analizadorSemantica1 = new Semantica1(controladorSQL, controladorTokenError, analizadorSemantica2);
        analizadorAmbito = new Ambito(controladorSQL, controladorTokenError, arreglos, analizadorSemantica1, analizadorSemantica2);
        analizadorAmbito.iniciarAmbito();
        analizadorSintaxis = new Sintaxis(
                urlLog,
                analizadorLexico.obtenerOperToken(),
                analizadorLexico.obtenerContadorIdentificadores(),
                controladorTokenError,
                analizadorAmbito);
        analizadorSintaxis.iniciarSintaxis();
        //analizadorSemantica1.iniciarSemantica1();
        controladorTokenError.actualizarTablas();
        controladorSQL.cerrarConexion();
        reproducir();
        nombreExcel = "Semantica2";
        analizadorSemantica2.imprimirReglas();
        imprimirArreglos();
    }//GEN-LAST:event_btnCompilarActionPerformed

    
    private void imprimirArreglos(){
        ArrayList<String> listOfKeys = arreglos.keySet().stream().collect(
                Collectors.toCollection(ArrayList::new));
        ArrayList<Arreglo> listOfValues = arreglos.values().stream().collect(
                Collectors.toCollection(ArrayList::new));
        System.err.println("LLAVE\tID\tAMBITO\tINC\tINICIO\tFIN");
        for (int i = 0; i < listOfValues.size(); i++) {
            System.err.print(listOfKeys.get(i)+"\t");
            System.err.print(listOfValues.get(i).getId()+"\t");
            System.err.print(listOfValues.get(i).getAmbito()+"\t");
            System.err.print(listOfValues.get(i).getIncremento()+"");
            for (int j = 0; j < listOfValues.get(i).getDimensiones().size(); j++) {
                System.err.print("\t["+listOfValues.get(i).getDimensiones().get(j).getPosicion()+"]");
                System.err.print(listOfValues.get(i).getDimensiones().get(j).getInicio()+"\t");
                System.err.print(listOfValues.get(i).getDimensiones().get(j).getFin()+"\n\t\t\t");
            }
            System.err.println();
        }           
    }
    
    private void establecerUltimaPrueba() {
        if (jTextArea1.getText() != "") {
            String pruebaActual = jTextArea1.getText();
            File archivo = new File("UltimaPrueba.txt");
            if (archivo.exists()) {
                archivo.delete();
            }
            BufferedWriter bw;
            try {
                bw = new BufferedWriter(new FileWriter("UltimaPrueba.txt"));
                bw.write(pruebaActual);
                bw.close();
            } catch (IOException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void btnXlsxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXlsxActionPerformed
        generarExcel = new GenerarExcel();
        generarExcel.generarExcel(
                controladorTokenError.obtenerArregloTokens(),
                controladorTokenError.obtenerArregloErrores(),
                analizadorLexico.obtenerContadoresLexico(),
                analizadorLexico.obtenerContadoresPorLineaLexico(),
                analizadorSintaxis.obtenerContadorDiagramasSintaxis(),
                analizadorAmbito.obtenerContadorEstructurasAmbito(),
                analizadorSemantica1, analizadorSemantica2, nombreExcel);
        if (jRBExcel.isSelected()) {
            try {
                Desktop.getDesktop().open(new File("MarcoAlejandroMarcialCoronado-"+nombreExcel+".xls"));
            } catch (IOException ex) {

            }
        } else {
            try {
                Desktop.getDesktop().open(new File(".."));
            } catch (IOException ex) {

            }
        }


    }//GEN-LAST:event_btnXlsxActionPerformed

    private void btnTablaSimbolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaSimbolosActionPerformed
        TablaSimbolosMySQL ts = new TablaSimbolosMySQL();
        ts.setVisible(true);
    }//GEN-LAST:event_btnTablaSimbolosActionPerformed

    private void btnAbrirLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirLogActionPerformed
        String ruta = "logs/" + urlLog;
        if (!new File(ruta).exists()) {

        } else {
            if (jRBLexico.isSelected()) {
                ruta += "/" + urlLog + "-Lexico.txt";
            } else if (jRBSintaxis.isSelected()) {
                ruta += "/" + urlLog + "-[Sintaxis-Ambito-Semantica1].txt";
            }
            try {
                Desktop.getDesktop().open(new File(ruta));
            } catch (IOException ex) {

            }
        }
    }//GEN-LAST:event_btnAbrirLogActionPerformed

    private void btnEjecutarUltimaPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarUltimaPruebaActionPerformed
        jTextArea1.setText("");
        File ultimaPrueba = new File("UltimaPrueba.txt");
        if (ultimaPrueba.exists()) {
            FileReader archivos = null;
            try {
                archivos = new FileReader(ultimaPrueba);
                BufferedReader leer = new BufferedReader(archivos);
                try {
                    String aux = leer.readLine();
                    jTextArea1.append(aux);
                    while ((aux = leer.readLine()) != null) {
                        jTextArea1.append("\n" + aux);
                    }
                    btnCompilarActionPerformed(null);
                } catch (IOException ex) {
                    Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    archivos.close();
                } catch (IOException ex) {
                    Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnEjecutarUltimaPruebaActionPerformed

    private void cargarTextArea() {
        jTextArea1.requestFocus();
        NumeroLinea numeroLinea = new NumeroLinea(jTextArea1);
        jSPTextArea.setRowHeaderView(numeroLinea);
    }

    private void reproducir() {
        try {
            File f = new File("src/fuerzabruta.wav");
            AudioInputStream audioIn = AudioSystem.getAudioInputStream(f);
            Clip clip = AudioSystem.getClip();
            clip.open(audioIn);
            clip.start();
        } catch (IOException | LineUnavailableException | UnsupportedAudioFileException e) {

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirLog;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCompilar;
    private javax.swing.JButton btnEjecutarUltimaPrueba;
    private javax.swing.JButton btnTablaSimbolos;
    private javax.swing.JButton btnXlsx;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabelErrores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRBExcel;
    private javax.swing.JRadioButton jRBLexico;
    private javax.swing.JRadioButton jRBSintaxis;
    private javax.swing.JScrollPane jSPTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelTokens;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCompilar;
    private javax.swing.JPanel panelErrores;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JPanel panelTablas;
    private javax.swing.JPanel panelTextArea;
    private javax.swing.JPanel panelTokens;
    private javax.swing.JScrollPane scrollPaneErrores;
    private javax.swing.JScrollPane scrollPaneTokens;
    private javax.swing.JTable tablaErrores;
    private javax.swing.JTable tablaTokens;
    // End of variables declaration//GEN-END:variables
}